### ISSUE TITLE
群晖7.0安装的最新测试版、矿神套件版，在群晖里都无法建立新文件夹和移动文件夹。请问怎么解决？？读写权限都已经给了

### ISSUE THREAD

**Issue by BLINGXIN** [cloud-fs/cloud-fs.github.io#1]
群晖7.0安装的最新测试版、矿神套件版，在群晖里都无法建立新文件夹和移动文件夹。请问怎么解决？？
![微信图片_20230806003129](https://github.com/cloud-fs/cloud-fs.github.io/assets/33460197/1cb17af2-c682-474e-84a9-240df3617dd9)

**Comment by liang31555** [comment]
同问

**Comment by link2fun** [comment]
不要在 FileStation 里面操作, 其他地方都可以操作, 局域网 smb 公网 webdav
其他应用挂载也能用, 就是 FileStation 不行

**Comment by liang31555** [comment]
这是来自QQ邮箱的假期自动回复邮件。您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by liang31555** [comment]
这是来自QQ邮箱的假期自动回复邮件。您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
