### ISSUE TITLE
安卓版的如何使用？

### ISSUE THREAD

**Issue by Pengkaniu** [cloud-fs/cloud-fs.github.io#10]
不是apk，不知道怎么安装啊，没有说明

**Comment by YUNDAN21** [comment]
同问

**Comment by free-150** [comment]
@YUNDAN21 @YUNDAN21 
我是用这个 https://github.com/sublaim/clouddrive2 安装成功的，以前看网上教程头都大，这个很方便。

**Comment by YUNDAN21** [comment]
> @YUNDAN21 @YUNDAN21 
> 我是用这个 https://github.com/sublaim/clouddrive2 安装成功的，以前看网上教程头都大，这个很方便。

感谢🙏

**Comment by Dracocc** [comment]
> @YUNDAN21 @YUNDAN21 我是用这个 https://github.com/sublaim/clouddrive2 安装成功的，以前看网上教程头都大，这个很方便。

是删掉了吗，链接进去是空的
