### ISSUE TITLE
win10挂载到本地盘用smb共享文件每次重启需要手动共享

### ISSUE THREAD

**Issue by jingaobao** [cloud-fs/cloud-fs.github.io#114]
win10挂载到本地盘用smb共享文件每次重启需要手动共享

**Comment by cloud-fs** [comment]
这是Windows smb server的问题。Windows启动的时候smb server早于clouddrive的服务启动，启动的时候并没有clouddrive挂载的盘，所以就不会共享clouddrive的挂载盘，之后即使clouddrive服务启动了，smb server也不会重新把缺失的共享再加回来。

**Comment by XuShuaiLiu** [comment]
有办法解决这个问题么 我这边原本win10并不会有这个问题 换了win11就出现了
