### ISSUE TITLE
win10安装运行后，打开gui页面卡在loding界面然后会跳出一堆下载dll文件的提示，下载以后还是用不了

### ISSUE THREAD

**Issue by Dabai2007** [cloud-fs/cloud-fs.github.io#12]
![image](https://github.com/cloud-fs/cloud-fs.github.io/assets/133517982/3bb10701-48ac-4a4e-a793-cb658fc2d90e)

**Comment by zzbakkk** [comment]
彻底关掉退出IDM

**Comment by zzbakkk** [comment]
关掉IDM  不要让它跳出来接管 就好了

**Comment by Eliauk365** [comment]
在【选项】-【文件类型】-【自动开始下载下列文件类型的文件】中将DLL移除就行了
