### ISSUE TITLE
添加123云盘出错

### ISSUE THREAD

**Issue by Arukassss** [cloud-fs/cloud-fs.github.io#122]
授权页登录之后返回
{
    "code": 401,
    "message": "access Token Invalid",
    "data": null,
    "x-traceID": "fb83a74d-b731-49d0-8653-25c072c00e44_kong-db-86bcfd649c-bc7l2"
}
无法添加

**Comment by cloud-fs** [comment]
这是123网盘授权页的一个小bug，解决方法时先重新登录一下123网盘官方web端，再重新授权
