### ISSUE TITLE
macos挂载无法写入文件

### ISSUE THREAD

**Issue by leon1208** [cloud-fs/cloud-fs.github.io#19]
总是报下面的错误，有人知道该怎么设置吗
<img width="885" alt="截屏2023-10-02 22 37 30" src="https://github.com/cloud-fs/cloud-fs.github.io/assets/7778712/55681024-e937-43df-8b6c-30f544e39e4d">

**Comment by ShakeChanDev** [comment]
同样

**Comment by lihuaihe** [comment]
这个问题修复了吗？现在还是一样的提示这个问题
