### ISSUE TITLE
Macos 使用终端进入挂载云盘会卡死导致云盘挂载退出

### ISSUE THREAD

**Issue by FocusProgram** [cloud-fs/cloud-fs.github.io#21]
<img width="677" alt="image" src="https://github.com/cloud-fs/cloud-fs.github.io/assets/44283663/9244ed9f-8e80-424d-8ddd-d34a11cab432">

使用terminal登入终端，执行cd命令，挂载的阿里云盘会卡死退出

**Comment by taotieren** [comment]
参考 Arch Linux 的配置说明，按步骤检查配置

**Comment by FocusProgram** [comment]
参考Arch Linux设置了UID、GID还是一样的错误

**Comment by FocusProgram** [comment]
> 参考 Arch Linux 的配置说明，按步骤检查配置

参考Arch Linux设置了UID、GID还是一样的错误
