### ISSUE TITLE
退出后无法登陆

### ISSUE THREAD

**Issue by chamwie** [cloud-fs/cloud-fs.github.io#29]
显示密码或用户名错误，我密码是保存在chrome里面的应该没问题，我现在卡在登陆界面什么也做不了，也没用重置按钮，我是mac，把cd2整个文件夹删除重新下载后，打开网页端还是卡在我自己账号的登录界面
![IMG_0186](https://github.com/cloud-fs/cloud-fs.github.io/assets/42801479/64fae3f1-928c-42e7-9ba6-46432301183e)

**Comment by shenfeng0602** [comment]
一样的问题，求解决

**Comment by cloud-fs** [comment]
0.6.11在这个界面提供了重置按钮
