### ISSUE TITLE
新版本Web1.3.9.0安装后显示Web1.3.8.0

### ISSUE THREAD

**Issue by 3Kzpf** [cloud-fs/cloud-fs.github.io#30]
![image](https://github.com/cloud-fs/cloud-fs.github.io/assets/38251896/bfbd6685-cad4-4102-b9a9-692efe0f15fd)
![image](https://github.com/cloud-fs/cloud-fs.github.io/assets/38251896/040404eb-212e-4561-ac1a-c6bf9cc5b069)

**Comment by joinwuxiao** [comment]
退出重新登陆就好行了

**Comment by 3Kzpf** [comment]
确实好使
