### ISSUE TITLE
无法重置密码

### ISSUE THREAD

**Issue by difey** [cloud-fs/cloud-fs.github.io#38]
启动后自动进到登陆卡片，只有登录按钮，没有重置密码按钮
![image](https://github.com/cloud-fs/cloud-fs.github.io/assets/11038952/b47cc124-0ad4-477f-8c06-ba2df0e69d19)

**Comment by shenfeng0602** [comment]
一样的问题

**Comment by cloud-fs** [comment]
0.6.11已解决
