### ISSUE TITLE
加载阿里云，无法扫码登录

### ISSUE THREAD

**Issue by daviddalao** [cloud-fs/cloud-fs.github.io#4]
如题。但是登录网页版阿里云可以扫码登录。

**Comment by daviddalao** [comment]
扫clouddrive二维码直接跳到阿里云app下载页面

**Comment by liaaaa2** [comment]
好像是app的问题，可以通过微信扫码登录

**Comment by daviddalao** [comment]
微信扫描可登录，但无法本地挂载。

**Comment by daviddalao** [comment]
GeneralFailure can't init winfsp GeneralFailure("error init winfsp, please install winfsp first!")
