### ISSUE TITLE
Mac Plex 扫描/分析导致 CD2 掉挂载

### ISSUE THREAD

**Issue by x1ao4** [cloud-fs/cloud-fs.github.io#41]
我的设备是 Mac，在 Mac 上搭建了 Plex 服务器，并使用 CD2 按照说明将网盘（Webdav）挂载到了 Mac 本地，平时没问题，但是当 Plex 开始扫描挂载盘上的项目时经常引发掉挂载，就是本地挂载目录突然消失不见，找不到设置的本地挂载点文件夹了，但 CD2 的网页上显示挂载状态一切正常，没有异样，没有报错，此时卸载挂载点，重新挂载即可恢复正常。

还有 Plex 的分析任务也可能会导致掉挂载，情况和扫描任务是一样的，扫描和分析都会大量读取挂载目录的项目，此时就很容易发生掉挂载的情况，测试手动对单个项目执行分析操作是不会引发掉挂载的，但是 Plex 的计划任务在后台自动进行分析时，可能由于分析的项目过多，会引发掉挂载的情况，但也不是百分百，或者不是一分析就掉，而是需要处理一些项目后才会掉。

Mac 掉挂载的情况有很多 Mac 用户都有反应，我经过这两天的测试初步判断我的情况和 Plex 的扫描/分析任务有关，当 Plex 没有进行这些任务时，只是单纯的挂载然后使用 Plex 播放视频等均不会引发掉挂载，每次发生掉挂载时都是 Plex 在进行扫描或者在进行分析的时候。

**Comment by x1ao4** [comment]
测试有时候分析 10 多分钟就会掉挂载，有时候分析 30 分钟掉挂载，有时候分析超过 1 个小时也不会掉挂载，但我基本可以确定每次掉挂载的时候都有分析或扫描行为，我猜测是在分析或扫描时遇到某种特定的文件或异常时会导致掉挂载。

**Comment by SculptureTime** [comment]
> 测试有时候分析 10 多分钟就会掉挂载，有时候分析 30 分钟掉挂载，有时候分析超过 1 个小时也不会掉挂载，但我基本可以确定每次掉挂载的时候都有分析或扫描行为，我猜测是在分析或扫描时遇到某种特定的文件或异常时会导致掉挂载。

这两天我也正在折腾这玩意，环境一样，不过我最开始用的cloudmouter挂载，也会出现plex扫描的时候掉盘，现在用rclone扫描的时候不会掉了，你可以试试。但是我这边会出现扫描完成后挂几个小时莫名其妙掉盘，本来想试试这个，看来还不太行

**Comment by x1ao4** [comment]
> 现在用rclone扫描的时候不会掉了

我之前用的就是 rclone，用了快一年了都很稳定，最近升级了 1.65，有时候会掉，我就想试试 cd2，结果 cd2 掉的更严重，所以我现在把 rclone 退回了 1.64.2，目前没有出现过掉挂载的情况，但是我用的是阿里云盘，alist 阿里云限速，cd2 不限速，alist+rclone 是限速的，用 cd2 不限速，可是 cd2 现在老是掉，昨天掉了好多次，实在没法用，我就还是退回 rclone 了。

**Comment by SculptureTime** [comment]
> > 现在用rclone扫描的时候不会掉了
> 
> 我之前用的就是 rclone，用了快一年了都很稳定，最近升级了 1.65，有时候会掉，我就想试试 cd2，结果 cd2 掉的更严重，所以我现在把 rclone 退回了 1.64.2，目前没有出现过掉挂载的情况，但是我用的是阿里云盘，alist 阿里云限速，cd2 不限速，alist+rclone 是限速的，用 cd2 不限速，可是 cd2 现在老是掉，昨天掉了好多次，实在没法用，我就还是退回 rclone 了。

我也试试1.64.2，我没用阿里云盘，就不太清楚限速的问题了。我在知乎上好像看到你的教程了，感谢大佬的教程，不过自启不好用，可以改为plist。

**Comment by x1ao4** [comment]
> 不过自启不好用，可以改为plist

开机启动我已经改成 crontab 开机任务了，也很方便。

**Comment by ilovn** [comment]
我也遇到了,也是掉挂载问题

**Comment by cloud-fs** [comment]
升级到最新版，已解决
