### ISSUE TITLE
webdav协议的云盘容量显示出错

### ISSUE THREAD

**Issue by dong-dong6** [cloud-fs/cloud-fs.github.io#51]
![image](https://github.com/cloud-fs/cloud-fs.github.io/assets/73739354/b932f8f7-9adf-4c7c-92d8-790aa516460e)
显示为为10PB
webdav平台为https://wp.007irs.com/

**Comment by northsea4** [comment]
https://wp.007irs.com/ 看上去应该是用的Cloudreve，它的webdav服务没有实现配额(quota)接口，所以CloudDrive只能假设一个较大的容量。

实际上不少webdav服务都没有实现配额(quota)接口，比如alist、群晖自带的WebDAV等，我知道nextcloud是有实现的。
