### ISSUE TITLE
rapid upload error Server error 

### ISSUE THREAD

**Issue by NOwin111** [cloud-fs/cloud-fs.github.io#52]
rapid upload error Server error 115 rapid upload error from server statuscode: 402, status: 4, errmsg: userid/filesize/target/pickcode invalid

挂载的115网盘，上传提示这个错误，请问是什么问题？

**Comment by XiaoWangShu2012** [comment]
重新登陆

**Comment by NOwin111** [comment]
> 重新登陆

果然是，重新扫码登录115后，就没问题了。感谢

**Comment by helo1220** [comment]
> 重新登陆
 你好 我也是同样的提示，挂载网盘到群晖里，用刮削软件刮了数据，上传的图片全部出这个提示 重新扫描登录也不行

**Comment by NOwin111** [comment]
> > 重新登陆
> > 你好 我也是同样的提示，挂载网盘到群晖里，用刮削软件刮了数据，上传的图片全部出这个提示 重新扫描登录也不行

操作的开始，要先扫码，然后用有备份的文件上传测试一下，没有问题再批量，否则直接开干中途报错卡住就有点麻烦。还可以尝试CD2的重启服务。然后非115会员有个5G限制。

**Comment by helo1220** [comment]
重新扫码登录我也试过了，甚至为了排除是115账号的问题，我还重新注册了一个115账号，还买了clouddrive的会员，都还是不行。请问下你是挂在nas里还是电脑里呢？
