### ISSUE TITLE
我在本地挂载后，啥也没做，怎么一直有下载任务

### ISSUE THREAD

**Issue by sunny-00001** [cloud-fs/cloud-fs.github.io#53]
![20240306_153226_153_copy](https://github.com/cloud-fs/cloud-fs.github.io/assets/28869215/3adabf31-26ff-4e3c-9811-fa7a4734a062)
![20240306_153307_760_copy](https://github.com/cloud-fs/cloud-fs.github.io/assets/28869215/759a24d2-5666-4361-97b8-88f71c7afd21)
好像程序会在后台下载我本地的文件？

**Comment by gexiaopeng** [comment]
应该是你本地的程序dopus.exe在下载文件，文件保存的路径正好是cd2本地挂载的目录，对cd2来说，就是在下载。

**Comment by sunny-00001** [comment]
我测试了一下，那个仅仅是因为dopus打开了Clouddrive2挂载在本地的目录
个人建议将系统任务下面加一个菜单“访问任务”，不然容易引起歧义
![图片](https://github.com/cloud-fs/cloud-fs.github.io/assets/28869215/1e1e6cee-780f-40af-8d36-6fe64667588b)
还有就是上传和下载记录里没有实时下载速度，我只有通过第三方工具才知道，建议加上

**Comment by gexiaopeng** [comment]
> 我测试了一下，那个仅仅是因为dopus打开了Clouddrive2挂载在本地的目录 个人建议将系统任务下面加一个菜单“访问任务”，不然容易引起歧义 ![图片](https://private-user-images.githubusercontent.com/28869215/315222490-1e1e6cee-780f-40af-8d36-6fe64667588b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTEwNzU5MjgsIm5iZiI6MTcxMTA3NTYyOCwicGF0aCI6Ii8yODg2OTIxNS8zMTUyMjI0OTAtMWUxZTZjZWUtNzgwZi00MGFmLThkMzYtNmZlNjQ2Njc1ODhiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzIyVDAyNDcwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWViY2Y1OWUxZDY1Njc4ZjdkNDU4MTIzZWI4MDRiOGVmM2I4ODQ4NmY0ZWJiZjVjNWQ0ZmM4ZTk4NGU1OThjYmQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.fw5OO0DEK99eDWDEw4VBDgXKG-Szoa8jclzdoXTyayI) 还有就是上传和下载记录里没有实时下载速度，我只有通过第三方工具才知道，建议加上

不是有全局速度吗，这个就是上传或者下载的总速度
