### ISSUE TITLE
建议支持universal跨网盘秒传

### ISSUE THREAD

**Issue by Eri--Wang** [cloud-fs/cloud-fs.github.io#54]
所有支持秒传的云盘都能够实现秒传，技术的关键在于通过文件在一个网盘的hash值得到其在另一个网盘的不同类型的hash值，这个功能的实现需要维护一个多种hash之间的mapping数据库。本地上传到网盘时，也可以根据文件partial hash查询到此文件在网盘的id，这样也可以实现本地上传到网盘的真正秒传。第一次碰到的文件无法秒传，此时则收集文件的各种hash，并上传到hash mapping数据库，便于后人使用。

**Comment by cloud-fs** [comment]
cd2不会存储任何形式和内容的用户数据
