### ISSUE TITLE
群晖挂载115网盘后，从本地上传文件一直报错rapid upload error Server error 115 rapid upload error from server statuscode: 402, status: 4, errmsg: userid/filesize/target/pickcode invalid

### ISSUE THREAD

**Issue by helo1220** [cloud-fs/cloud-fs.github.io#57]
我是用群晖的clouddrive挂载的115网盘，再把115网盘内的电影挂载的我的电脑里用刮削软件刮数据，但是最近几天上传同步就出这个提示，请问是什么问题
![Uploading 屏幕截图 2024-03-17 081423.png…]()

**Comment by helo1220** [comment]
![Uploading 屏幕截图 2024-03-17 081423.png…]()

**Comment by helo1220** [comment]
报这个错
rapid upload error Server error 115 rapid upload error from server statuscode: 402, status: 4, errmsg: userid/filesize/target/pickcode invalid

**Comment by changanning** [comment]
windows挂载115也是爆这个错，无法上传了

**Comment by lgclgclgc111** [comment]
我也遇到这个问题了 windows挂载115也是爆这个错 无法上传 nas遇到这个问题也无法上传了

**Comment by lgclgclgc111** [comment]
以115盘为主力盘的基本处于不能用状态

**Comment by gexiaopeng** [comment]
重新挂载115网盘再试一试，我遇到几次错误重新挂载就可以了。

**Comment by TangTab** [comment]
我知道，应该是你在app上把115的登录删除了，重新登录下就行
