### ISSUE TITLE
百度云盘上的文件内容无法修改

### ISSUE THREAD

**Issue by Eri--Wang** [cloud-fs/cloud-fs.github.io#58]
重新步骤
1. 挂载百度云盘到本地磁盘
2. 上传一个文本文件a.txt
3. 从资源管理器中用记事本打开a.txt,并编辑
4. 保存并关闭记事本

问题：百度网盘上的文件a.txt不会被修改, CloudDrive WEB页面可以看到对应的upload task发生致命错误。
PS： 这个问题导致几乎无法对百度网盘上的媒体库进行刮削
PPS： AList没有这个问题

**Comment by cloud-fs** [comment]
更新版本，已解决
