### ISSUE TITLE
clouddrive2的0.6.10版本不是说新增123云盘吗

### ISSUE THREAD

**Issue by sunny-00001** [cloud-fs/cloud-fs.github.io#61]
刚更新的0.6.10版本没有看到有支持123云盘
![20240329_192026_758](https://github.com/cloud-fs/cloud-fs.github.io/assets/28869215/68144cb3-f57d-4f7b-9a91-2670571bccb1)

**Comment by sunuuc** [comment]
没有

**Comment by Eri--Wang** [comment]
![image](https://github.com/cloud-fs/cloud-fs.github.io/assets/6417404/4137fb9b-e323-474c-b48b-341a7c40242f)

**Comment by Purewo** [comment]
> 刚更新的0.6.10版本没有看到有支持123云盘 ![20240329_192026_758](https://private-user-images.githubusercontent.com/28869215/318034826-68144cb3-f57d-4f7b-9a91-2670571bccb1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI5ODQyMDgsIm5iZiI6MTcxMjk4MzkwOCwicGF0aCI6Ii8yODg2OTIxNS8zMTgwMzQ4MjYtNjgxNDRjYjMtZjU3ZC00ZjdiLTlhOTEtMjY3MDU3MWJjY2IxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDEzVDA0NTE0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTlmOWZlYzY5NGJlMzUyOWY1NTJiODMxMmJkY2ZlNTE0ZTc5YWUzOGJlMGRjM2JiMDNkZDRmNTEyOTk5Y2M0MjEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.fPuSlqPZg392hdh3tK7eb-Q5cVbl6NI1lgexp1lURyk)

需要清除浏览器本地缓存，你的webui版本号不对

**Comment by Purewo** [comment]
去设置里面找到这个网站清除一下就行，简单一点直接f12 选中“网络”，点击 禁用缓存 ，CTRL+R结束
