### ISSUE TITLE
手机版注册不了

### ISSUE THREAD

**Issue by QiBowen2008** [cloud-fs/cloud-fs.github.io#63]
一直卡在这里，只有手机版这样

**Comment by QiBowen2008** [comment]
![Uploading Screenshot_20240404_210856.jpg…]()

**Comment by QiBowen2008** [comment]
![Screenshot_20240404_210856](https://github.com/cloud-fs/cloud-fs.github.io/assets/109896442/d60aca24-7f38-4de6-970d-d138208f39ef)

**Comment by cloud-fs** [comment]
检查你的网络
