### ISSUE TITLE
mac挂载延迟特别严重

### ISSUE THREAD

**Issue by lizonglin2010** [cloud-fs/cloud-fs.github.io#65]
使用mac将阿里云挂载为本地后，使用finder访问网盘目录加载时间非常耗时，比clouddrive网页访问阿里云要慢得多，基本达不到所谓的方便（clouddrive浏览器访问阿里云进入目录基本是秒切，但finder需要花费的时间要长的多，加载时间很多需要30s甚至更长）
是因为预下载或者加载缩略图的原因吗？

<img width="203" alt="屏幕快照 2024-04-09 的 00 34 01 上午" src="https://github.com/cloud-fs/cloud-fs.github.io/assets/85780935/a5feb8d1-8327-4324-8b99-56103922cb1f">

**Comment by cloud-fs** [comment]
Finder最好用列表模式，关闭缩略图预览
