### ISSUE TITLE
已经root的安卓手机，安装cloudDrive后还是提示“未获得root权限，不能本地挂载”

### ISSUE THREAD

**Issue by Minghao-li** [cloud-fs/cloud-fs.github.io#72]
你好，
我在安卓10的原生aosp上想预装这个apk。
但是我已经root了手机，还是会提示未获得root权限。
请问我要在安卓系统上挂载本地文件，有没有什么说明吗？

**Comment by cloud-fs** [comment]
需要有类似magisk这样的root管理器，运行的时候会弹出root管理器的授权界面，要通过root管理器授权root，才能获取root权限
