### ISSUE TITLE
上传文件失败 提示重新登录115 但是重新登录后 这些任务还是不能继续上传

### ISSUE THREAD

**Issue by ysidyn** [cloud-fs/cloud-fs.github.io#76]
上传文件失败 提示重新登录115 但是重新登录后 这些任务还是不能继续上传
![微信图片_20240426204137](https://github.com/cloud-fs/cloud-fs.github.io/assets/97540380/a463fb40-b48b-4c7d-b3c9-aa1c568afd05)

**Comment by cloud-fs** [comment]
115网盘无法上传下载的说明：
CloudDrive2的扫码登录是以115的Linux客户端身份扫码登录，115最近对Linux客户端扫码登录做了限制，同时只允许一个Linux客户端登录，多次登录会禁止以前登录的Linux客户端上传文件，所以115登录需注意以下规则：
1. 一个115账号只能扫码登录到一个CloudDrive账号，多个CloudDrive账号扫码登录同一个115账号会有上传失败的问题
2. 同一个CloudDrive账号的多处运行并且扫码登录相同115账号时，需选择同步账号到云端，只需扫码登录一次，其它终端通过云同步获取115登录信息，如果不同步账号到云端，就会有多次115扫码登录，同样会遇到无法上传的问题。CloudDrive登录时如果没有选择同步账号到云端，请先在Web界面退出登录，退出时勾选同时退出CloudFS账号，再次登录是可选择账号信息同步到云端。
3. 115手机app退出登录后，该app扫码登录的所有终端都会自动退出，需要重新扫码登录

结论：一个115账号只能扫码添加给一个CloudDrive账号，同一个CloudDrive账号的多处登录需打开云端数据同步，115手机app退出登录后需要重新扫码登录CloudDrive。使用过程中碰到115无法上传或者下载的情况，请先尝试重新添加115。

**Comment by ysidyn** [comment]
好的 我试试 谢谢

---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2024年04月27日 11:22 |
| 收件人 | ***@***.***> |
| 抄送人 | ysidyn ***@***.***>,
Author ***@***.***> |
| 主题 | Re: [cloud-fs/cloud-fs.github.io] 上传文件失败 提示重新登录115 但是重新登录后 这些任务还是不能继续上传 (Issue #76) |

115网盘无法上传下载的说明：
CloudDrive2的扫码登录是以115的Linux客户端身份扫码登录，115最近对Linux客户端扫码登录做了限制，同时只允许一个Linux客户端登录，多次登录会禁止以前登录的Linux客户端上传文件，所以115登录需注意以下规则：

一个115账号只能扫码登录到一个CloudDrive账号，多个CloudDrive账号扫码登录同一个115账号会有上传失败的问题
同一个CloudDrive账号的多处运行并且扫码登录相同115账号时，需选择同步账号到云端，只需扫码登录一次，其它终端通过云同步获取115登录信息，如果不同步账号到云端，就会有多次115扫码登录，同样会遇到无法上传的问题。CloudDrive登录时如果没有选择同步账号到云端，请先在Web界面退出登录，退出时勾选同时退出CloudFS账号，再次登录是可选择账号信息同步到云端。
115手机app退出登录后，该app扫码登录的所有终端都会自动退出，需要重新扫码登录

结论：一个115账号只能扫码添加给一个CloudDrive账号，同一个CloudDrive账号的多处登录需打开云端数据同步，115手机app退出登录后需要重新扫码登录CloudDrive。使用过程中碰到115无法上传或者下载的情况，请先尝试重新添加115。

**Comment by xueli12** [comment]
> 115网盘无法上传下载的说明： CloudDrive2的扫码登录是以115的Linux客户端身份扫码登录，115最近对Linux客户端扫码登录做了限制，同时只允许一个Linux客户端登录，多次登录会禁止以前登录的Linux客户端上传文件，所以115登录需注意以下规则：
> 
> 1. 一个115账号只能扫码登录到一个CloudDrive账号，多个CloudDrive账号扫码登录同一个115账号会有上传失败的问题
> 2. 同一个CloudDrive账号的多处运行并且扫码登录相同115账号时，需选择同步账号到云端，只需扫码登录一次，其它终端通过云同步获取115登录信息，如果不同步账号到云端，就会有多次115扫码登录，同样会遇到无法上传的问题。CloudDrive登录时如果没有选择同步账号到云端，请先在Web界面退出登录，退出时勾选同时退出CloudFS账号，再次登录是可选择账号信息同步到云端。
> 3. 115手机app退出登录后，该app扫码登录的所有终端都会自动退出，需要重新扫码登录
> 
> 结论：一个115账号只能扫码添加给一个CloudDrive账号，同一个CloudDrive账号的多处登录需打开云端数据同步，115手机app退出登录后需要重新扫码登录CloudDrive。使用过程中碰到115无法上传或者下载的情况，请先尝试重新添加115。

@cloud-fs 大大您好，请教一下可否通过配置文件修改默认登录设备呀？应该如何修改呢，比如我想使用mac或者android，应该填什么字段呀？
![image](https://github.com/cloud-fs/cloud-fs.github.io/assets/51438016/6ad18c36-9762-4ce1-902b-58d411b33aab)
