### ISSUE TITLE
挂载123云盘和天翼云盘，挂当地盘，出现电子表格文件，有的可以正常打开编辑使用，有的一打开就闪退，

### ISSUE THREAD

**Issue by vm669** [cloud-fs/cloud-fs.github.io#84]
挂载天翼云盘，挂当地盘，出现电子表格文件，
有的可以正常打开编辑使用，
有的一打开就闪退，
先进入excel再打开改文件，也是如此闪退。

换123云盘也一样。

**Comment by cloud-fs** [comment]
xls文件有这个问题，这是已知问题，后续会修复，xlsx文件没问题
