### ISSUE TITLE
点击云盘文件夹提示需要登录，但是邮箱不可编辑并且是异常的邮箱地址

### ISSUE THREAD

**Issue by 2548085610** [cloud-fs/cloud-fs.github.io#86]
![image](https://github.com/cloud-fs/cloud-fs.github.io/assets/52267428/b237d81f-277f-4805-b19b-43e6434da246)

**Comment by cloud-fs** [comment]
清空浏览器缓存刷新web版本，这个版本太早了，不支持编辑
