### ISSUE TITLE
建议优化一下webui

### ISSUE THREAD

**Issue by sunny-00001** [cloud-fs/cloud-fs.github.io#87]
1.建议统一图标配色
2.网盘文件夹设置汉化不彻底
![图片](https://github.com/cloud-fs/cloud-fs.github.io/assets/28869215/58d770c6-5384-4142-a821-2273960e323c)
3.合理利用右边侧边栏
![图片](https://github.com/cloud-fs/cloud-fs.github.io/assets/28869215/f12501c9-7091-4731-b468-3004bf7ee195)
当未选中任何网盘或者全部选中时，侧边栏显示系统信息
当在根目录选中网盘时，侧边栏显示网盘设置窗格
当在网盘目录中选择文件或文件夹时，侧边栏显示详细信息窗格
 1.将侧边栏改成详细信息窗格。
缩小预览图，将文件或文件夹的元属性（名称、状态、修改时间、访问时间、创建时间、类型、位置、大小、描述、属性、预览图等）分组排列
 2.将侧边栏改成网盘设置窗格
将网盘最大下载线程、最小读取长度、最大缓存值、访问超时时间、最大上传任务量、缓存路径等设置项依次分组排列

**Comment by sunny-00001** [comment]
新增的密码修改功能建议重新排版一下，或者做成单独窗口
![图片](https://github.com/cloud-fs/cloud-fs.github.io/assets/28869215/7490306e-75ec-429a-aacd-bec513da097e)

**Comment by cloud-fs** [comment]
后面版本会对webui做专门的优化
