### ISSUE TITLE
备份文件不一致

### ISSUE THREAD

**Issue by for7GG** [cloud-fs/cloud-fs.github.io#88]
有webdav向阿里云盘备份，webdav删除文件后文件不会同步
![1717061668799](https://github.com/cloud-fs/cloud-fs.github.io/assets/10189846/1f4f6eed-df24-4218-8852-d32b0ddcfe72)

![1717061687758](https://github.com/cloud-fs/cloud-fs.github.io/assets/10189846/b791fa5c-7f30-47b1-a5ef-64f71b45357e)

**Comment by for7GG** [comment]
版本已是最新（0.7.0-beta2(Web1.5.0.2)）点击停止和重新开始按钮  也不会有任何变化

**Comment by cloud-fs** [comment]
只有在CloudDrive2内部进行的删除操作才能被监控到并且同步到目的文件夹，扫描目录的不支持删除
