### ISSUE TITLE
前天开始上传到天翼云盘就失败

### ISSUE THREAD

**Issue by tony027wh** [cloud-fs/cloud-fs.github.io#89]
前天开始上传到天翼云盘就失败，是天翼云更新了么？
![image](https://github.com/cloud-fs/cloud-fs.github.io/assets/149884543/da5a990d-845b-4165-8e22-4945f4fab716)

**Comment by Vstory** [comment]
看tg群通知

**Comment by cloud-fs** [comment]
0.7.1已修复
